celo-org/celo-bls-snark-rs

- bls/src/bls/keys.rs
- bls/src/curve/hash/try_and_increment.rs
- bls/src/lib.rs
- go/bls.go
- go/bls.h
- go/bls_test.go
* Public keys are stored compressed, with the last bit signifying
whether y is the greatest of the two options.
* Try-and-increment now generates enough random bits so each attempt to
generate field elements or group elements should succeed in expected 2
tries and rejects invalid results. This lets us use one less prf
execution.
* Aggregation with subtraction is exposed.
* Unit tests pass.
* Added a new test for compressed public keys.
> feat: optimizations (some due to Noah's comments)

- bls/examples/pop.rs
Mistakenly added a pk print in the pop, which causes tests to fail.
> fix: removes unneeded print of pk in pop

- go/bls_android.go
- go/bls_android_64.go
Geth expects an android target go file, which currently is too fine-grained.
> fix: makes android build compatible with geth

- go/bls.go
Input sizes weren't validated for private keys, public keys and signatures.
> fix: validates input sizes in Go module

- bls/algebra/src/hash/composite.rs
- bls/algebra/src/lib.rs
- zexe/algebra/src/fields/edwards_bls12/fr.rs
- zexe/algebra/src/fields/edwards_sw6/fr.rs
- zexe/dpc/src/crypto_primitives/crh/bowe_hopwood.rs
- zexe/dpc/src/crypto_primitives/crh/mod.rs
- zexe/dpc/src/gadgets/crh/bowe_hopwood.rs
- zexe/dpc/src/gadgets/crh/mod.rs
- zexe/snark-gadgets/src/fields/fp.rs
- zexe/snark-gadgets/src/fields/fp12.rs
- zexe/snark-gadgets/src/fields/fp2.rs
- zexe/snark-gadgets/src/fields/fp6_3over2.rs
- zexe/snark-gadgets/src/fields/mod.rs
- zexe/snark-gadgets/src/groups/curves/twisted_edwards/edwards_bls12.rs
- zexe/snark-gadgets/src/groups/curves/twisted_edwards/edwards_sw6.rs
- zexe/snark-gadgets/src/groups/curves/twisted_edwards/mod.rs
- zexe/snark-gadgets/src/groups/curves/twisted_edwards/test.rs
- zexe/snark-gadgets/src/groups/mod.rs
- zexe/snark-gadgets/src/utils.rs
Implements Bowe-Hopwood hash, as described in the [Zcash protocol specification](https://github.com/zcash/zips/blob/master/protocol/protocol.pdf).
Most of the implementation is done in Zexe and contains the following changes:
1. Adds native and gadget implementations, and needed changes to relevant traits.
2. Describes MODULUS_MINUS_ONE_DIV_TWO for fields where was not needed before.
3. Modifies TryAndIncrement in bls-zexe to use this variant.
Added tests in a similar fashion to the other Pedersen hash.
> Adds Bowe-Hopwood hash

- zexe/r1cs-std/src/fields/fp.rs
- zexe/r1cs-std/src/fields/fp12.rs
- zexe/r1cs-std/src/fields/fp2.rs
- zexe/r1cs-std/src/fields/fp6_3over2.rs
- zexe/r1cs-std/src/fields/mod.rs
- zexe/r1cs-std/src/groups/curves/twisted_edwards/mod.rs
- zexe/r1cs-std/src/select.rs
* Adds add_bool_with_coeff
* Makes 3_bit_cond_neg receive precomputed b0b1
* Makes Bowe-Hopwood more efficient
> Optimizes Bowe-Hopwood

- bls/algebra/examples/pop_csv.rs
- bls/algebra/src/bls/keys.rs
- bls/algebra/src/curve/cofactor.rs
- bls/algebra/src/curve/hash/mod.rs
- bls/algebra/src/curve/hash/try_and_increment.rs
- bls/algebra/src/hash/direct.rs
- bls/snark/Cargo.toml
- bls/snark/src/encoding/mod.rs
- bls/snark/src/lib.rs
- go/bls.go
- go/bls.h
- go/bls_android.go
- go/bls_arm.go
- go/bls_arm64.go
- go/bls_arm7.go
- go/bls_darwin.go
- go/bls_darwin64.go
- go/bls_linux.go
- go/bls_linux386.go
- go/bls_linux64.go
- go/bls_mips.go
- go/bls_mips64.go
- go/bls_mips64le.go
- go/bls_mipsle.go
- go/bls_test.go
- go/bls_windows.go
- go/bls_windows64.go
* Moves signatures to G1, public keys to G2
* Adds epoch SNARK encoding.
- Fixes #83 
- Fixes #84
> Switch signature from G2 to G1

- go/go.mod
The correct path needs a trailing `go`
> Fix go.mod

- bls/Cargo.toml
- bls/gadgets/Cargo.toml
- bls/gadgets/README.md
- bls/gadgets/src/bitmap.rs
- bls/gadgets/src/bls.rs
- bls/gadgets/src/lib.rs
- bls/gadgets/src/y_to_bit.rs
- bls/snark/src/lib.rs
- Creates a new `gadgets` crate which will contain all gadgets. This should improve compilation times, as well as have better separation between things that are gadgets and higher level circuits which are application specific
- Adds point compression gadget from @kobigurk's PR https://github.com/celo-org/bls-zexe/pull/73
> Refactor Gadgets to Standalone crate

- bls/gadgets/src/bitmap.rs
- bls/gadgets/src/bls.rs
- bls/gadgets/src/hash_to_group.rs
- bls/gadgets/src/lib.rs
- bls/gadgets/src/slice_update.rs
- bls/gadgets/src/validator.rs
Adds gadget which enforces that a slice's elements are replaced by another slice's elements at the indexes where a bitmap is set to 1. We will use this for checking that validator diffs are computed correctly.
Based on the code from https://github.com/celo-org/bls-zexe/pull/73.
> Add Slice Update gadget

- crates/bls-crypto/examples/simple_signature.rs
- crates/bls-crypto/src/bls/keys.rs
- crates/bls-crypto/src/lib.rs
- crates/bls-gadgets/src/bitmap.rs
- crates/bls-gadgets/src/bls.rs
- crates/bls-gadgets/src/hash_to_group.rs
- crates/bls-gadgets/src/lib.rs
- crates/epoch-snark/src/epoch_block.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/src/gadgets/pack.rs
- crates/epoch-snark/src/gadgets/single_update.rs
- crates/epoch-snark/src/lib.rs
- Removes slices of references from the APIs. They make every datatype really awkward to work with and do not provide any significant advantage. Also, taking a reference and cloning inside is generally bad practice so I've removed that as well. It's better if the caller explicitly clones so that there's no hidden costs. This might mean that we have an allocation overhead in the FFI, but I recommend we worry about that later, when we actually test the FFI performance.
- The gadgets previously were not sufficiently equipped to handle being called during the parameter generation phase. We add a heuristic for getting inner booleans which says "if any of the inner variables is None, then assume we're in the setup phase". I think this is a fair assumption to make for our boolean constraint …
> Improve FFI API & ensure setup works

- Cargo.lock
- crates/epoch-snark/examples/proof.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/tests/e2e.rs
As title. Paper benchmarks should be redone after this PR, given that we have:
1. added more constraints by fixing some previous bugs
2. improved efficiency by using groth w/o zk
> feat(prover): use no-zk groth16 prover

- Cargo.lock
- crates/bls-crypto/src/curve/hash/try_and_increment.rs
- crates/bls-gadgets/Cargo.toml
- crates/bls-gadgets/src/bitmap.rs
- crates/bls-gadgets/src/bls.rs
- crates/bls-gadgets/src/hash_to_group.rs
- crates/epoch-snark/Cargo.toml
- crates/epoch-snark/examples/proof.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/api/setup.rs
- crates/epoch-snark/src/api/verifier.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/hash_to_bits.rs
- crates/epoch-snark/src/gadgets/pack.rs
- crates/epoch-snark/src/gadgets/single_update.rs
As title, using the [tracing](https://github.com/tokio-rs/tracing) crate.
We use `info` logs for the top level API calls, and spanned `debug` and `trace` logs for lower level information (`span` basically groups together all calls within that scope)
Example log below
[tracing.log](https://github.com/celo-org/bls-zexe/files/4337622/tracing.log)
> Adds tracing

- crates/bls-gadgets/src/hash_to_group.rs
- crates/epoch-snark/Cargo.toml
- crates/epoch-snark/examples/constraints.rs
- crates/epoch-snark/examples/proof.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/api/setup.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/src/gadgets/proof_of_compression.rs
- crates/epoch-snark/src/gadgets/single_update.rs
- crates/epoch-snark/tests/e2e.rs
As discussed, we want to allow the system to run in the following 2 modes:
- 1 proof, 1 setup, but CRH->XOF in SW6
- 2 proofs (one inside another), 2 setups, but CRH->XOF in BLS12-377 (much faster)
This PR enables that to happen by changing the high-level API components to view the HashToBits proof as an optional "helper". If it is present, 2 proofs will be generated, otherwise only 1 is.
This is done on the basis that the prover overhead will justify the overhead from having to do 2 setups (1 per snark).
`cargo run --release --example proof 30 10 true` will generate 10 epoch proofs for 30 validators with hashproofs in BLS12-377 (2-proof method), toggling the last argument to `false` will do the hashproofs in SW6.
> Optionally hash in SW6

- Cargo.lock
- Cargo.toml
- crates/bls-gadgets/src/bls.rs
- crates/bls-gadgets/src/smaller_than.rs
- crates/epoch-snark/examples/constraints.rs
Depends on https://github.com/scipr-lab/zexe/pull/151
Zexe latest master requires us to us `to_bits` instead of `to_bits_strict`, which costs slightly more constraints.
> examples: calculate number of constraints from empty circuit

- crates/bls-crypto/Cargo.toml
- crates/bls-crypto/src/bls/keys.rs
- crates/bls-crypto/src/lib.rs
- crates/bls-crypto/src/test_helpers.rs
- crates/bls-gadgets/Cargo.toml
- crates/bls-gadgets/src/bls.rs
- crates/bls-gadgets/src/lib.rs
- crates/epoch-snark/Cargo.toml
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/tests/fixtures.rs
As title. n+1 pairings instead of 2n for n messages. We had that already implemented for the SNARK code.
Also refactored some test helpers for convenience.
> Batched BLS Verification

- crates/bls-crypto/src/lib.rs
- go/bls/bls.go
- go/bls/bls.h
- go/bls/bls_test.go
As title.
- re-generated `bls.h` from cbindgen, better than having hand-written headers.
- Added a new `Message` type which should contain all the data per epoch (seal, extradata, aggregate pubkey and aggregate signature)
- Added a `BatchVerifyEpochs` that takes an array of `Message` along with which hashing mode it should use, transforms the data to the correct format and calls the underlying rust function.
NOTE: Using cgo with pointers is tricky! You need  to allocate the memory _in c_ (with a C.malloc) call, and then write directly to the pointer as done [here](https://github.com/celo-org/bls-zexe/pull/130/files#diff-8e469dd8fbfdccde93b553dbecb08742R260-R276)
> Batch BLS Verification - Go Bindings

- Cargo.lock
As title, in order to get the performance improvements from https://github.com/scipr-lab/zexe/pull/163#issuecomment-607683082
> chore: bump zexe to latst master

- go/bls/bls.go
- go/bls/bls.h
As title. Android does not have `ulong` datatypes. https://circleci.com/gh/celo-org/celo-blockchain/31359
Will unblock https://github.com/celo-org/celo-blockchain/pull/969
> fix(bls): cast lengths to int so that the functions can compile on android

- crates/bls-crypto/examples/simple_signature.rs
- crates/bls-crypto/src/bls/cache.rs
- crates/bls-crypto/src/bls/ffi.rs
- crates/bls-crypto/src/bls/public.rs
- crates/bls-crypto/src/bls/secret.rs
- crates/bls-crypto/src/bls/signature.rs
- crates/bls-crypto/src/lib.rs
- crates/epoch-snark/src/api/ffi/utils.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/encoding.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/tests/fixtures.rs
Working on making the codebase more idiomatic
- get_pk -> as_ref
- from_pk -> from (same for Signature and Private Key)
- Inner types replaced with a newtype that wraps around them instaed of having a different name per inner type
- Make signature aggregation take IntoIterator, so that we do not need to make extra allocations when calling it with signatures which are part of another struct
- Some extra docs added
> feat(bls-crypto): implement common traits and improve abstractions

- crates/bls-crypto/Cargo.toml
- crates/bls-crypto/examples/simple_signature.rs
- crates/bls-crypto/src/bls/cache.rs
- crates/bls-crypto/src/bls/ffi.rs
- crates/bls-crypto/src/bls/public.rs
- crates/bls-crypto/src/bls/secret.rs
- crates/bls-crypto/src/bls/signature.rs
- crates/bls-crypto/src/lib.rs
- crates/epoch-snark/src/api/ffi/utils.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/encoding.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/tests/fixtures.rs
Adds zexe serialization for our basic crypto types. Depends on https://github.com/celo-org/bls-zexe/pull/135.
> Key & Signature Serialization

- crates/bls-crypto/src/bls/public.rs
- crates/bls-crypto/src/bls/signature.rs
Fixes https://github.com/celo-org/bls-zexe/issues/149.
Adds tests that the old serialization/deserialization logic matches the new implementation, besides the problematic cases.
> Fixes point compression logic and uses upstream Zexe logic instead

- crates/bls-crypto/src/bls/keys.rs
As title. I found the `*_bytes3` naming confusing, the lazy_statics were unnecessary, and the deserialization was return the `x, y` elements, while in order for it to "perfectly" match it should return the Group element
Tests and fixed functionality looks good otherwise.
> test(keys): make tests clearer

- .circleci/config.yml
- Cargo.lock
- crates/bls-crypto/Cargo.toml
- crates/bls-crypto/src/hash_to_curve/try_and_increment.rs
The deployed Celo version's hash-to-curve takes the sign bit from a different position than the upstream Zexe logic. This PR adds a compatibility mode that allows to use the upstream Zexe version by patching the appropriate bits.
Adds tests with the old hasher and compares results.
> Adds compat mode to support the deployed Celo blockchain

- crates/bls-crypto/src/bls/cache.rs
- crates/bls-crypto/src/bls/public.rs
- Adds tests for the cache
- The cache's hashset now uses a WrappedPublicKey type which implements the byte level equality, while the normal public key derives it from its underlying group element datatype
> test(cache): add tests and improve PublicKey PartialEq

- README.md
- crates/bls-gadgets/src/bitmap.rs
- crates/bls-gadgets/src/bls.rs
- crates/bls-gadgets/src/hash_to_group.rs
- crates/bls-gadgets/src/lib.rs
- crates/bls-gadgets/src/utils.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/encoding.rs
- crates/epoch-snark/src/epoch_block.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/hash_to_bits.rs
- crates/epoch-snark/src/gadgets/pack.rs
- crates/epoch-snark/src/gadgets/proof_of_compression.rs
- crates/epoch-snark/src/gadgets/single_update.rs
Slight cleanup on the library's top level interface
> refactor: move utility functions to their own module

- crates/bls-crypto/src/bls/public.rs
- crates/bls-crypto/src/bls/secret.rs
- crates/bls-crypto/src/bls/signature.rs
As title, uses the internal `Sum` implementation
> perf(bls): use Sum to calculate aggregate pubkeys/sigs

- Cargo.lock
- crates/bls-gadgets/src/y_to_bit.rs
There was some logic which could be extracted to a function, plus some redundant `is_some()` calls.
> Simplify Y to Bit Gadget

- crates/bls-crypto/src/bls/cache.rs
- crates/bls-snark-sys/src/cache.rs
- crates/bls-snark-sys/src/lib.rs
- crates/bls-snark-sys/src/serialization.rs
- crates/bls-snark-sys/src/signatures.rs
Allows consumers to deserialize public keys while using the LRU cache. Also, enlarges the cache to have a bigger margin.
> Adds deserialize_public_key_cached

- .circleci/config.yml
- crates/bls-gadgets/src/bls.rs
- crates/bls-gadgets/src/y_to_bit.rs
- crates/epoch-snark/examples/proof.rs
- crates/epoch-snark/src/api/mod.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/single_update.rs
- crates/epoch-snark/tests/e2e.rs
In order to have the circuit have a maximum number of epochs, but still support proving a smaller number of epochs, we add the support of padding with dummy epochs.
Regular epochs have index > 1.
These epochs have the following properties:
* Index = 0.
* Public keys are all the generator of G2.
We change the circuit logic to perform the following:
* Instead of enforcing the epoch index is sequential, it enforces it only if the new index is not zero.
* In the processing loop, `previous_epoch_index`, `previous_public_keys` and `previous_maximum_non_signers` are updated only if the index is not zero.
* The aggregated public key that's used in the miller loop for that epoch is chosen to be the generator for G2. This is conditionally chosen based on the epoch index being zero.
* The message …
> Feature: support padding with dummy epochs

- crates/bls-crypto/src/bls/signature.rs
- crates/bls-crypto/src/lib.rs
If there are more messages that public keys only the messages that have public keys are verified because of how zip works. Also, allocate (message hash, pubkey) `Vec` using `with_capacity` to avoid needing to re-alloc.
> Ensure all msgs are batch verified + don't re-alloc

- crates/bls-snark-sys/src/snark/epoch_block.rs
- crates/bls-snark-sys/src/snark/mod.rs
- crates/epoch-snark/src/encoding.rs
- crates/epoch-snark/src/epoch_block.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/tests/fixtures.rs
This PR adds support for padding the validator set by passing another maximum validators parameter.
This is almost 100% based on @lucasege's work.
We had a bug in `encode_public_key` where it checks `c1 == half` instead of the updated `c1 == 0` as mentioned in https://github.com/celo-org/celo-bls-snark-rs/issues/149.
Tests on the encoding.
> Implement CIP22 padding

- crates/bls-gadgets/Cargo.toml
- crates/bls-gadgets/src/bitmap.rs
- crates/bls-gadgets/src/bls.rs
- crates/bls-gadgets/src/hash_to_group.rs
- crates/bls-gadgets/src/utils.rs
- crates/bls-gadgets/src/y_to_bit.rs
- crates/epoch-snark/src/gadgets/epoch_bits.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/src/gadgets/pack.rs
- crates/epoch-snark/src/gadgets/single_update.rs
Each test now uses a wrapper to initializes constraint tracing. Tracing annotations have also been added to some relevant functions which generate constraints.
Tests modified to fail printed unsatisfied constraints
https://github.com/celo-org/celo-bls-snark-rs/issues/184
> Add tracing for tests

- crates/bls-gadgets/src/bls.rs
- crates/epoch-snark/src/epoch_block.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/single_update.rs
This PR disallows using the padding public key as a public key in a location where a bit is active.
This prevents an attack where a malicious prover could use the padding public keys, which are defined currently to be the generator, as part of the used public keys in a block. This is bad, since the secret key against these is known - it's just `one`.
An alternative solution would have been to use an element with an unknown discrete log against the generator as the padding value. This is worse, in my opinion, since we'd have to convince that the discrete log is unknown. It's somewhat OK if we use a hash to derive it, but still requires to inspire confidence in it.
Added a test that shows the proofs fail when the padding value is used.
> fix: disallow the padding value as a public key in an activated location

- crates/bls-crypto/src/hash_to_curve/try_and_increment_cip22.rs
- crates/bls-snark-sys/src/signatures.rs
Two additions to the API
* CRH hash (Bowe-Hopwood Pedersen hash)
* Added counter to return value of composite hash (cip 22 version)
> feat: adds API methods relevant for slashing
