- bls/src/bls/keys.rs
- bls/src/curve/hash/mod.rs
- bls/src/curve/hash/try_and_increment.rs
- bls/src/hash/composite.rs
- bls/src/hash/direct.rs
- bls/src/hash/mod.rs
- go/bls.go
- go/bls_android.go
- go/bls_android_64.go
- go/bls_linux.go
Makes the Go binding link to the correct subdirectory in the Rust library.
Adds a key to make the hash a PRF.
> feat: modifies linking per os and makes the hash a PRF

- go/bls.go
Zero length messages are currently broken.
> Handles zero-length messages correctly

- bls/src/bls/keys.rs
- go/bls.go
Signatures are now lexicographically ordered and compressed.
> feat: compresses signatures

- bls/src/bls/keys.rs
Serialization was done in a confusing way.
> fix: serializes more clearly

- bls/Cargo.toml
- bls/examples/pop_csv.rs
- bls/src/curve/hash/try_and_increment.rs
Previously, y coordinates was chosen to be the greatest when signing.
> Correctly randomly sample elements of G2

- bls/algebra/Cargo.toml
- bls/algebra/src/bls/keys.rs
- bls/algebra/src/curve/hash/mod.rs
- bls/algebra/src/curve/hash/try_and_increment.rs
- bls/algebra/src/hash/composite.rs
- bls/algebra/src/hash/direct.rs
- bls/algebra/src/hash/mod.rs
- tools/bls_test_vectors/go.mod
- tools/bls_test_vectors/go.sum
- tools/bls_test_vectors/main.go
Fixes #55 and #58.
Unit tests passes, added a test vector from the reference implementation of Blake2x.
> Implements blake2x, removes PRF key and changes terminology to xof

- go/bls.go
- go/bls_test.go
While not shown to be exploitable, the API has been improved to be safer - more nil checks and empty slices check.
Tests have been modified to acomodate.
> Adds more asserts for correctness and tests

- bls/algebra/Cargo.toml
- bls/algebra/examples/pop.rs
- bls/algebra/examples/pop_csv.rs
- bls/algebra/examples/simple_signature.rs
- bls/algebra/src/bls/keys.rs
- bls/algebra/src/curve/cofactor.rs
- bls/algebra/src/curve/hash/try_and_increment.rs
- bls/algebra/src/hash/composite.rs
- bls/algebra/src/lib.rs
- bls/snark/Cargo.toml
- bls/snark/src/encoding/mod.rs
- bls/snark/src/gadgets/bls/mod.rs
- bls/snark/src/gadgets/mod.rs
- bls/snark/src/lib.rs
1. Updates the repo to latest Zexe master
2. Docs + Tests refactor / expansion
Part of splitting https://github.com/celo-org/bls-zexe/pull/73 in smaller reviewable PRs
> Update BLS & Algebra

- bls/gadgets/Cargo.toml
- bls/gadgets/src/hash_to_group.rs
- bls/gadgets/src/lib.rs
- Adds Hash to Group gadget from @kobigurk's PR https://github.com/celo-org/bls-zexe/pull/73.
Tests were initially commented out, I have made an attempt at reviving them. Endianness seems to be the problem here.
> Hash to Group Gadget

- .circleci/config.yml
- crates/epoch-snark/src/gadgets/hash_to_bits.rs
> tests(hash to bits): add e2e groth test

- Cargo.lock
- crates/bls-gadgets/Cargo.toml
- crates/bls-gadgets/src/bitmap.rs
- crates/bls-gadgets/src/bls.rs
- crates/epoch-snark/examples/proof.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/api/setup.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/hash_to_bits.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/src/gadgets/single_update.rs
- crates/epoch-snark/tests/e2e.rs
> test(bitmap): add test using groth

- Cargo.lock
- crates/bls-crypto/Cargo.toml
- crates/bls-gadgets/Cargo.toml
- crates/epoch-snark/Cargo.toml
- crates/epoch-snark/examples/proof.rs
> feat: use parallel features

- crates/bls-crypto/src/bls/ffi.rs
- crates/bls-crypto/src/bls/keys.rs
- crates/bls-crypto/src/bls/mod.rs
- crates/bls-crypto/src/lib.rs
As title. 
I have added a file for FFI helpers, and made the functions slightly more flexible (can now take both` &[PublicKey]` and `&[&PublicKey]` by using `Borrow`).
> Batch BLS FFI

- crates/bls-crypto/Cargo.toml
- crates/epoch-snark/Cargo.toml
This is to prevent verbose logging on Geth usage.
> Adds a print-trace feature to only conditionally enable tracing

- crates/bls-crypto/src/curve/hash/try_and_increment.rs
We're doing some big changes, so we want to make sure we don't introduce any breaking change.
> Adds test vectors for hash to curve

- crates/bls-crypto/src/bls/public.rs
- crates/bls-crypto/src/bls/secret.rs
- crates/bls-crypto/src/bls/signature.rs
- crates/bls-crypto/src/hash_to_curve/mod.rs
- crates/bls-crypto/src/hash_to_curve/try_and_increment.rs
- crates/bls-crypto/src/hashers/composite.rs
- crates/bls-crypto/src/hashers/direct.rs
- crates/bls-crypto/src/hashers/mod.rs
- crates/bls-crypto/src/lib.rs
- crates/bls-crypto/src/test_helpers.rs
- crates/bls-gadgets/src/hash_to_group.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/gadgets/hash_to_bits.rs
Some more docs added, plus doctests
> Finalize BLS Crypto Docs

- .circleci/config.yml
- crates/bls-crypto/src/bls/signature.rs
- crates/bls-snark-sys/src/snark/epoch_block.rs
- crates/bls-snark-sys/src/snark/mod.rs
- crates/epoch-snark/examples/constraints.rs
- crates/epoch-snark/examples/proof.rs
- crates/epoch-snark/src/api/mod.rs
- crates/epoch-snark/src/api/prover.rs
- crates/epoch-snark/src/api/setup.rs
- crates/epoch-snark/src/api/verifier.rs
- crates/epoch-snark/src/encoding.rs
- crates/epoch-snark/src/epoch_block.rs
- crates/epoch-snark/src/gadgets/epoch_bits.rs
- crates/epoch-snark/src/gadgets/epoch_data.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/hash_to_bits.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/src/gadgets/pack.rs
- crates/epoch-snark/src/gadgets/proof_of_compression.rs
- crates/epoch-snark/src/gadgets/single_update.rs
- crates/epoch-snark/src/lib.rs
- crates/epoch-snark/tests/e2e.rs
- crates/epoch-snark/tests/fixtures.rs
This PR completes my review of the repository. I have added docs to everything and minimized the public API to only expose the minimum necessary functions.
> Reorganize exports & add docs to Epoch SNARK

- Cargo.lock
- crates/bls-crypto/Cargo.toml
- crates/bls-crypto/benches/batch_bls.rs
(obviously it is faster than the single sig one)
> test(bls-crypto): add benchmark for batched bls verification

- crates/epoch-snark/src/api/mod.rs
Exposing some datatypes for consuming applications
> feat: make curves & params types public

- Cargo.lock
- crates/bls-crypto/Cargo.toml
- crates/bls-crypto/src/bls/public.rs
- crates/bls-crypto/src/bls/signature.rs
- crates/bls-gadgets/Cargo.toml
- crates/bls-snark-sys/Cargo.toml
- crates/epoch-snark/Cargo.toml
Zexe has updated their writer interface, and so this aligns it.
> Updates to latest zexe

- crates/bls-gadgets/src/bitmap.rs
- crates/bls-gadgets/src/hash_to_group.rs
- crates/bls-gadgets/src/utils.rs
- crates/bls-gadgets/src/y_to_bit.rs
- crates/epoch-snark/src/gadgets/epoch_bits.rs
- crates/epoch-snark/src/gadgets/epochs.rs
- crates/epoch-snark/src/gadgets/mod.rs
- crates/epoch-snark/src/gadgets/single_update.rs
Expanded r1cs gadget documentation for clarity/maintainability
https://github.com/celo-org/celo-bls-snark-rs/issues/193
> More gadget documentation

- Cargo.lock
- crates/bls-crypto/Cargo.toml
- crates/bls-gadgets/Cargo.toml
- crates/bls-gadgets/src/bitmap.rs
- crates/bls-gadgets/src/hash_to_group.rs
- crates/bls-gadgets/src/utils.rs
- crates/bls-snark-sys/Cargo.toml
- crates/epoch-snark/Cargo.toml
A few panics can seamlessly be folded in the Error case of their enclosing Result
> Remove a couple panics
